# ESP32C6 Basic Configuration Example
#
# Required hardware:
#  - ESPHome XIAO Base
#  - XIAO ESP32C6
#  - SH1106 OLED 64x128 0.96" Display

# Board Configuration
esphome:
  name: "esp32c6-base"
  friendly_name: "ESP32C6 Base"
  platformio_options:
    platform: https://github.com/lucaskatayama/platform-espressif32.git#feat/seeed_xiao_esp32c6.json

esp32:
  board: seeed_xiao_esp32c6
  flash_size: 4MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: false

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "!ha_encryption_key!"

# ESPHome OTA
ota:
  - platform: esphome
    password: "!my_ota_password!"

# Network Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP32C6 Base Fallback Hotspot"
    password: "!my_generate_password!"

captive_portal:

# Enable WebUI
web_server:
  port: 80

# OLED Display
display:
  - platform: ssd1306_i2c
    model: "SH1107 128x64"
    address: 0x3C
    rotation: 90
    offset_y: 96
    offset_x: 0
    lambda: |-
      it.line(0, 0, 128, 64);
      it.rectangle(5, 5, 10, 10);
      it.circle(118, 54, 5);
      it.rectangle(0, 0, 128, 64);
      it.filled_circle(((int)id(uptime_sensor).state)*10 % 128, it.get_height() / 2, 10);

# Sensors
binary_sensor:
  # Buttons
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button Left"
    filters:
      - delayed_off: 100ms
    disabled_by_default: true
    on_press:
      - logger.log: "LEFT"
  - platform: gpio
    pin:
      number: GPIO1
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button OK"
    filters:
      - delayed_off: 100ms
    disabled_by_default: true
    on_press:
      - logger.log: "OK"
  - platform: gpio
    pin:
      number: GPIO2
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button Right"
    filters:
      - delayed_off: 100ms
    disabled_by_default: true
    on_press:
      - logger.log: "RIGHT"

sensor:
  # Uptime
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor
    update_interval: 1.0s
  # Wifi Signal
  - platform: wifi_signal
    id: wifi_strength
    name: "Wifi Signal"
    update_interval: 60s

text_sensor:
  # Wifi Info
  - platform: wifi_info
    ip_address:
      id: wifi_ip
      name: "Wifi IP"
    mac_address:
      id: wifi_mac
      name: "Wifi MAC"
